#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

#include "../common/scene_data.glsl"
#include "../common/random.glsl"
#include "../common/camera.glsl"
#include "../common/path_sample.glsl"

#include "options.glsl"

#include "../mlmc/path_length_mlmc.glsl"

#define STORE_RNG true

layout(binding = 1, set = 0, rgba32f) uniform image2D image;
layout(binding = 12, set = 0, rgba32f) uniform image2D diff_image;

vec3 unbiasedEstimator(uint sample_count) {
    ViewRay view_ray = generateViewRay(vec2(gl_LaunchIDEXT.xy), vec2(gl_LaunchSizeEXT.xy), sceneData.inv_view, sceneData.inv_proj, payload.rng_state);
    initPayload(view_ray.origin, view_ray.direction);

    vec3 color = vec3(0);
    for (int i = 0; i < sample_count; i++) {
        color += takeSample(options.recursion_depth);
    }
    color /= sample_count;
    return color;
}

vec3 biasedEstimator(uint sample_count, uint mlmc_method) {
    if (mlmc_method == 0) {
        return pathLengthMlmc(sample_count, options.biased_path_length);
    }
    return vec3(1, 0, 0);
}

vec3 diffEstimator(uint sample_count, uint mlmc_method) {
    if (mlmc_method == 0) {
        return pathLengthDiffMlmc(sample_count, options.biased_path_length, options.recursion_depth);
    }
    return vec3(1, 0, 0);
}

void main() {
    payload.rng_state = imageLoad(rng_tex, ivec2(gl_LaunchIDEXT.xy));

    if (!options.do_mlmc) {
        uint accum_count = options.accumulated_frame_count;

        vec3 color = unbiasedEstimator(options.samples_per_pixel);
        if (accum_count != 0) {
            vec3 prev_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy)).xyz;
            color = (accum_count * prev_color + color) / (accum_count + 1);
        }
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(color, 1.0));
    } else {
        uint accum_count = options.accumulated_frame_count;

        vec3 diff = diffEstimator(options.diff_samples_per_pixel, options.mlmc_method);
        if (accum_count != 0) {
            vec3 prev_diff = imageLoad(diff_image, ivec2(gl_LaunchIDEXT.xy)).xyz;
            diff = (accum_count * prev_diff + diff) / (accum_count + 1);
        }
        imageStore(diff_image, ivec2(gl_LaunchIDEXT.xy), vec4(diff, 1.0));

        vec3 color = biasedEstimator(options.samples_per_pixel, options.mlmc_method);
        if (accum_count != 0) {
            vec3 prev_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy)).xyz;
            color = (accum_count * prev_color + color) / (accum_count + 1);
        }
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(color, 1.0));
    }

    if (STORE_RNG) {
        imageStore(rng_tex, ivec2(gl_LaunchIDEXT.xy), payload.rng_state);
    }
}