#ifndef ALTERED_PHASE_BUFFER_GLSL
#define ALTERED_PHASE_BUFFER_GLSL

// Generated by scripts/similarity_relations/build_similarity_buffer.pl.
// Do not edit by hand; re-run the converter after regenerating the
// canonical altered_phase_coefficients.glsl from similarity_relations.py.

const int NUM_KEYS = 49;
const int NUM_COEFFS = 360;

const float G_KEYS[NUM_KEYS] = float[](
    0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3,
    0.3, 0.4, 0.4, 0.4, 0.4, 0.4, 0.5, 0.5,
    0.5, 0.5, 0.5, 0.6, 0.6, 0.6, 0.6, 0.6,
    0.6, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7,
    0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8,
    0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9,
    0.9
);

const float ALPHAS[NUM_KEYS] = float[](
    0.9, 1, 0.8, 0.9, 1, 0.7, 0.8, 0.9,
    1, 0.6, 0.7, 0.8, 0.9, 1, 0.6, 0.7,
    0.8, 0.9, 1, 0.5, 0.6, 0.7, 0.8, 0.9,
    1, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1,
    0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1,
    0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,
    1
);

// Backing storage for the tabulated phase functions. Populated once at
// startup from resources/similarity/altered_phase_coefficients.bin (the
// SSBO payload after that file's header and key arrays). std430 layout
// means consecutive floats with no padding, so the payload is just
// COEFFS then CDF then TOTALS, each a packed float array.
layout(set = 0, binding = 15, std430) readonly buffer SimilarityCoefficientBuffer {
    float coeffs[NUM_KEYS * NUM_COEFFS];
    float cdf[NUM_KEYS * NUM_COEFFS];
    float totals[NUM_KEYS];
} similarity_buf;

float fetchPhaseCoefficient(int tableIdx, int i) {
    return similarity_buf.coeffs[tableIdx * NUM_COEFFS + i];
}

#endif
