#ifndef VULKAN_RAYTRACING_RENDERTARGETTYPE_HPP
#define VULKAN_RAYTRACING_RENDERTARGETTYPE_HPP

namespace RtEngine {
    enum RenderTargetType {
        RAYTRACE_TARGET,
        COMPUTE_TARGET,
        RNG_TARGET,
        MOMENT_TARGET,
    };
} // RtEngine

#endif //VULKAN_RAYTRACING_RENDERTARGETTYPE_HPP