#ifndef VULKAN_RAYTRACING_RENDERTARGETKEYS_HPP
#define VULKAN_RAYTRACING_RENDERTARGETKEYS_HPP

#define MAIN_TARGET "main"
#define RNG_TARGET "rng"
#define DIFF_TARGET "diff"

#endif //VULKAN_RAYTRACING_RENDERTARGETKEYS_HPP