#ifndef VULKAN_RAYTRACING_RENDERTARGETKEYS_HPP
#define VULKAN_RAYTRACING_RENDERTARGETKEYS_HPP

#define MAIN_TARGET_KEY "main"
#define RNG_TARGET_KEY "rng"
#define DIFF_TARGET_KEY "diff"
#define MLMC_TARGET_KEY "mlmc_out"

#endif //VULKAN_RAYTRACING_RENDERTARGETKEYS_HPP