runner:
  scene_name: ref_scene_homo_volume
renderer:
  recursion_depth: 20
metal_rough:
  normal_mapping: false
  next_event_estimation: true
  bsdf_importance_sampling: false
  russian_roulette: false