runner:
  scene_name: ref_scene_homo_volume
benchmark:
  biased_samples: 1024
  diff_samples: 512
  averaging_rounds: 10
renderer:
  recursion_depth: 20
mlmc:
  mlmc_mode: "path length"
  mlmc_present_mode: "combined"
  biased_path_length: 2
metal_rough:
  normal_mapping: false
  next_event_estimation: false
  bsdf_importance_sampling: false
  russian_roulette: false