Material:
  Recursion_Depth: 3
  Normal_Mapping: false
  Sample_Lights: true
  Sample_BSDF: true
  Russian_Roulette: false
  Denoising: false
  Samples_Per_Pixel: 3
  Shadows: true
  Dispersion: true
  Fresnel: true
Renderer:
  Scene: cornell_phong.yaml
