runner:
  scene_name: cloud_scene
renderer:
  recursion_depth: 20
mlmc:
  mlmc_mode: "path length"
  mlmc_present_mode: "combined"
  biased_path_length: 5
phong:
  shadows: true
  fresnel: true
  dispersion: true
metal_rough:
  normal_mapping: false
  next_event_estimation: false
  bsdf_importance_sampling: false
  russian_roulette: false