runner:
  scene_name: ref_scene_real_cloud
renderer:
  recursion_depth: 200
mlmc:
  mlmc_present_mode: "unbiased"
metal_rough:
  normal_mapping: false
  next_event_estimation: true
  bsdf_importance_sampling: true
  russian_roulette: false