runner:
  scene_name: ref_scene_hetero_volume
renderer:
  recursion_depth: 200
mlmc:
  mlmc_present_mode: "unbiased"
metal_rough:
  normal_mapping: false
  next_event_estimation: false
  bsdf_importance_sampling: false
  russian_roulette: false