runner:
  scene_name: ref_scene_big_light
benchmark:
  name: "all"
  expected_ref_samples: 262144
  biased_samples: 1024
  diff_samples: 0
  averaging_rounds: 1
renderer:
  recursion_depth: 20
mlmc:
  mlmc_present_mode: "unbiased"
metal_rough:
  normal_mapping: false
  next_event_estimation: true
  bsdf_importance_sampling: true
  russian_roulette: true