runner:
  scene_name: [[SCENE_NAME]]
benchmark:
  name: "[[NAME]]"
  expected_ref_samples: [[EXPECTED_SAMPLES]]
  biased_samples: 1024
  diff_samples: 512
  averaging_rounds: [[AVERAGING_ROUNDS]]
renderer:
  recursion_depth: [[RECURSION_DEPTH]]
mlmc:
  mlmc_mode: "similarity"
  mlmc_present_mode: "combined"
metal_rough:
  normal_mapping: false
  next_event_estimation: false
  bsdf_importance_sampling: true
  russian_roulette: true