import os
import sys

def add_meson_files(path):
    for dirpath, dirnames, filenames in os.walk(path):
        output_file = os.path.join(dirpath, 'meson.build')

        with open(output_file, 'w') as f:
            f.write("# This file is automatically generated from generate_meson_files.py\n\n")
            for dirname in dirnames:
                f.write(f"subdir('{dirname}')\n")
            f.write("\n")

            f.write("src += files(\n")
            for filename in filenames:
                if filename == "meson.build": continue;
                f.write(f"  '{filename}',\n")
            f.write(")\n")

def main():
    if len(sys.argv) != 2:
        print("Usage: python create_a_txt.py <target_directory>")
        sys.exit(1)

    target_dir = sys.argv[1]

    # Ensure the target directory exists
    os.makedirs(target_dir, exist_ok=True)
    add_meson_files(target_dir)

if __name__ == "__main__":
    main()
