runner:
  scene_name: cloud_scene
benchmark:
  name: "baseline"
  expected_ref_samples: 262144
  biased_samples: 1024
  diff_samples: 0
  averaging_rounds: 1
renderer:
  recursion_depth: 50
mlmc:
  mlmc_present_mode: "unbiased"
metal_rough:
  normal_mapping: false
  next_event_estimation: false
  bsdf_importance_sampling: false
  russian_roulette: false