#version 450
#extension GL_GOOGLE_include_directive : enable

#include "../common/random.glsl"

#define GLITCH_COLOR_COUNT 8

layout (binding = 0, rgba32f) uniform writeonly image2D target;
layout (binding = 1, rgba8) uniform readonly image2D src;

layout (local_size_x = 1, local_size_y = 256, local_size_z = 1) in;

bool doGlitch(vec3[GLITCH_COLOR_COUNT] glitch_colors, vec3 color) {
    bool do_glitch = false;
    float eps = 1e-2;
    for (int i = 0; i < GLITCH_COLOR_COUNT; i++) {
        if (all(lessThan(abs(color - glitch_colors[i]), vec3(eps)))) {
            do_glitch = true;
        }
    }
    return do_glitch;
}

void main()
{
    uint line_strength = 2;
    uint max_dist = 6;

    vec3 glitch_colors[GLITCH_COLOR_COUNT] = vec3[](
        vec3(208.0f / 256.0f, 86.0f / 256.0f, 87.0f / 256.0f), // red
        vec3(207.0f / 256.0f, 104.0f / 256.0f, 98.0f / 256.0f),
        vec3(225.0f / 256.0f, 129.0f / 256.0f, 76.0f / 256.0f), // orange
        vec3(215.0f / 256.0f, 162.0f / 256.0f, 112.0f / 256.0f),
        vec3(6.0f / 256.0f, 96.0f / 256.0f, 87.0f / 256.0f), // green        
        vec3(82.0f / 256.0f, 140.0f / 256.0f, 117.0f / 256.0f),
        vec3(75.0f / 256.0f, 193.0f / 256.0f, 160.0f / 256.0f), // blue
        vec3(93.0f / 256.0f, 195.0f / 256.0f, 160.0f / 256.0f)
    );

    int row = int(gl_GlobalInvocationID.y);
    ivec2 size = imageSize(target);

    if (row >= size.y)
        return;

    uint seed = 1385743257;
    uvec4 rng_state = uvec4(seed, seed * 2, seed * 3, seed * 4) + 5378947 * (row / line_strength);

    float rand = stepAndOutputRNGFloat(rng_state);

    int dist = int(round(rand * float(2 * max_dist))) - int(max_dist);

    if (dist > 0) {
        for (int i = size.x; i >= 0; i--) {
            ivec2 pixel = ivec2(i, row);
            vec3 c = imageLoad(src, pixel).xyz;

            if (doGlitch(glitch_colors, c)) {
                ivec2 new_pos_right = pixel + ivec2(dist, 0);
                ivec2 new_pos_left = pixel - ivec2(dist, 0);

                if (new_pos_right.x < size.x) {
                    imageStore(target, new_pos_right, vec4(c, 1));
                }

                if (new_pos_left.x >= 0) {
                    vec3 left_c = imageLoad(src, new_pos_left).xyz;
                    imageStore(target, pixel, vec4(left_c, 1));
                }
            } else {
                imageStore(target, pixel, vec4(c, 1));
            }
        }
    } else {
        for (int i = 0; i < size.x; i++) {
            ivec2 pixel = ivec2(i, row);
            vec3 c = imageLoad(src, pixel).xyz;

            if (doGlitch(glitch_colors, c)) {
                ivec2 new_pos_right = pixel - ivec2(dist, 0);
                ivec2 new_pos_left = pixel + ivec2(dist, 0);

                if (new_pos_left.x >= 0) {
                    imageStore(target, new_pos_left, vec4(c, 1));
                }

                if (new_pos_right.x < size.x) {
                    vec3 left_c = imageLoad(src, new_pos_right).xyz;
                    imageStore(target, pixel, vec4(left_c, 1));
                }
            } else {
                imageStore(target, pixel, vec4(c, 1));
            }
        }
    }
}
