#version 450
#extension GL_GOOGLE_include_directive : enable

layout (binding = 0, rgba32f) uniform writeonly image2D target;
layout (binding = 1, rgba32f) uniform readonly image2D biased_target;
layout (binding = 2, rgba32f) uniform readonly image2D diff_target;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(target);

    if (pixel.x >= size.x || pixel.y >= size.y)
        return;

    vec3 biased = imageLoad(biased_target, pixel).xyz;
    vec3 diff = imageLoad(diff_target, pixel).xyz;
    vec3 color = biased + diff;

    //imageStore(target, pixel, vec4(color, 1));
    imageStore(target, pixel, vec4(diff, 1));
}
