#ifndef CORRELATION_MODES_GLSL
#define CORRELATION_MODES_GLSL

const uint RESAMPLE_CORRELATION_MODE = 0;
const uint SAME_PATH_CORRELATION_MODE = 1;
const uint SKIP_DETERMINISTIC_CORRELATION_MODE = 2;
const uint SKIP_RANDOM_CORRELATION_MODE = 3;

#endif